// THE AUTOGENERATED LICENSE. ALL THE RIGHTS ARE RESERVED BY ROBOTS.

// WARNING: This file has automatically been generated on Tue, 30 Jul 2024 14:19:40 CST.
// Code generated by https://git.io/c-for-go. DO NOT EDIT.

package add

/*
#cgo CFLAGS: -I../../include
#cgo LDFLAGS: -L../../lib -ladd -Wl,-rpath,lib
#include "add.h"
#include <stdlib.h>
#include "cgo_helpers.h"
*/
import "C"
import "runtime"

// AddTwoNumber function as declared in include/add.h:1
func AddTwoNumber(a int32, b int32) int32 {
	ca, caAllocMap := (C.int)(a), cgoAllocsUnknown
	cb, cbAllocMap := (C.int)(b), cgoAllocsUnknown
	__ret := C.AddTwoNumber(ca, cb)
	runtime.KeepAlive(cbAllocMap)
	runtime.KeepAlive(caAllocMap)
	__v := (int32)(__ret)
	return __v
}
