// THE AUTOGENERATED LICENSE. ALL THE RIGHTS ARE RESERVED BY ROBOTS.

// WARNING: This file has automatically been generated on Tue, 30 Jul 2024 14:19:40 CST.
// Code generated by https://git.io/c-for-go. DO NOT EDIT.

#include "add.h"
#include <stdlib.h>
#pragma once

#define __CGOGEN 1

