// THE AUTOGENERATED LICENSE. ALL THE RIGHTS ARE RESERVED BY ROBOTS.

// WARNING: This file has automatically been generated on Tue, 30 Jul 2024 13:00:57 CST.
// Code generated by https://git.io/c-for-go. DO NOT EDIT.

/*
Package add provides Go bindings for add.h
*/
package add
