// THE AUTOGENERATED LICENSE. ALL THE RIGHTS ARE RESERVED BY ROBOTS.

// WARNING: This file has automatically been generated on Tue, 30 Jul 2024 12:57:57 CST.
// Code generated by https://git.io/c-for-go. DO NOT EDIT.

/*
Package mgmt provides Go bindings for xengine_mgmt_op.h
*/
package mgmt
