// THE AUTOGENERATED LICENSE. ALL THE RIGHTS ARE RESERVED BY ROBOTS.

// WARNING: This file has automatically been generated on Tue, 30 Jul 2024 12:57:57 CST.
// Code generated by https://git.io/c-for-go. DO NOT EDIT.

package mgmt

/*
#cgo CFLAGS: -I.
#include "xengine_mgmt_op.h"
#include <stdlib.h>
#include "cgo_helpers.h"
*/
import "C"

// Xengine_alg_status as declared in mgmt/xengine_mgmt_op.h:84
type Xengine_alg_status struct {
	Random_status        int32
	Soft_alg_status      int32
	Dev_sm4_status       int32
	Dev_sm3_status       int32
	Dev_sm9_enc_status   int32
	Dev_sm9_sign_status  int32
	Dev_sm2_enc_status   int32
	Dev_sm2_sign_status  int32
	Card_sm2_enc_status  int32
	Card_sm2_sign_status int32
	Usb_status           int32
	Reserved             [60]byte
	ref32bf029e          *C.xengine_alg_status
	allocs32bf029e       interface{}
}

// Xengine_device_cfg as declared in mgmt/xengine_mgmt_op.h:92
type Xengine_device_cfg struct {
	Max_key_num    int32
	Device_config  uint32
	Reserved       [504]byte
	ref2f69cd7d    *C.xengine_device_cfg
	allocs2f69cd7d interface{}
}

// XEngineLicense_t as declared in mgmt/xengine_mgmt_op.h:108
type XEngineLicense_t struct {
	NVer           uint32
	NKeyIndex      uint32
	NOp            uint32
	NLicenseIndex  [8]byte
	NSeq           uint32
	NTotalNum      uint32
	NIncreasement  uint32
	UcRandom       [20]byte
	UcMagic        [20]byte
	ref7466438d    *C.XEngineLicense_t
	allocs7466438d interface{}
}

// XEngineDevLicense_t as declared in mgmt/xengine_mgmt_op.h:122
type XEngineDevLicense_t struct {
	NVer           uint32
	NType          uint32
	NIssueTime     uint64
	NStartTime     uint64
	NDeadTime      uint64
	NSeq           uint32
	UcSeqNum       [8]byte
	UcUser         [8]byte
	UcIssuer       [8]byte
	UcDevId        [32]byte
	UcMagic        [20]byte
	refc230d25e    *C.XEngineDevLicense_t
	allocsc230d25e interface{}
}

// XEngineKeyInfo_t as declared in mgmt/xengine_mgmt_op.h:132
type XEngineKeyInfo_t struct {
	BUsed          byte
	CAlg           byte
	BPub           byte
	BPrv           byte
	NBits          uint32
	ref9e381fbd    *C.XEngineKeyInfo_t
	allocs9e381fbd interface{}
}

// XEngineKeyInfoEx_t as declared in mgmt/xengine_mgmt_op.h:143
type XEngineKeyInfoEx_t struct {
	BUsed          byte
	CAlg           byte
	BPub           byte
	BPrv           byte
	NBits          uint32
	BKeyId         [192]byte
	refc14febe6    *C.XEngineKeyInfoEx_t
	allocsc14febe6 interface{}
}

// XENGINE_MgmtPasswd_t as declared in mgmt/xengine_mgmt_op.h:266
type XENGINE_MgmtPasswd_t struct {
	NLen           int32
	PPasswd        [64]byte
	ref1380ca00    *C.XENGINE_MgmtPasswd_t
	allocs1380ca00 interface{}
}
